# Generated by Django 4.1 on 2022-09-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_auction_alter_bid_user_alter_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_price',
            new_name='price',
        ),
    ]
